pipeline {
    agent any

    stages {
        
        stage('Checkout Code') {
            steps {
                git 'https://github.com/<your-username>/<your-repo>.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t <your-dockerhub-username>/jenkins-demo .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([string(credentialsId: 'dockerhub-pass', variable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u <your-dockerhub-username> --password-stdin'
                }
                sh 'docker push <your-dockerhub-username>/jenkins-demo'
            }
        }
    }
}
